<template>
  <div class="page">
    <el-card shadow="never">
      <div class="toolbar">
        <el-input v-model="query.keyword" placeholder="盘点单号" clearable style="width:180px" @keyup.enter="search" />
        <el-select v-model="query.warehouseId" clearable placeholder="仓库" style="width:180px" @change="search"><el-option v-for="warehouse in warehouses" :key="warehouse.id" :label="warehouse.name" :value="warehouse.id!" /></el-select>
        <el-select v-model="query.status" clearable placeholder="状态" style="width:130px" @change="search"><el-option v-for="item in statusOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select>
        <el-button type="primary" :icon="Search" @click="search">查询</el-button><el-button type="primary" plain :icon="Plus" @click="openCreate">新增盘点</el-button>
      </div>
      <el-table v-loading="loading" :data="records" border stripe>
        <el-table-column prop="docNo" label="盘点单号" width="170" /><el-table-column label="仓库" width="140"><template #default="{ row }">{{ row.warehouseName || warehouseName(row.warehouseId) }}</template></el-table-column><el-table-column prop="checkDate" label="盘点日期" width="120" /><el-table-column label="类型" width="100"><template #default="{ row }">{{ checkTypeLabel(row.checkType) }}</template></el-table-column><el-table-column prop="totalItems" label="品项数" width="90" align="right" /><el-table-column label="盘点金额" width="120" align="right"><template #default="{ row }">¥{{ money(row.totalAmount) }}</template></el-table-column><el-table-column prop="diffItems" label="差异品项" width="100" align="right" /><el-table-column label="差异金额" width="120" align="right"><template #default="{ row }">¥{{ money(row.diffAmount) }}</template></el-table-column><el-table-column label="状态" width="100" align="center"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="300" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="showDetail(row.id)">详情</el-button><el-button v-if="row.status === 'DRAFT'" link type="primary" @click="start(row)">开始盘点</el-button><el-button v-if="row.status === 'AUDITING'" link type="primary" @click="openResult(row)">录入结果</el-button><el-button v-if="row.status === 'AUDITING'" link type="success" @click="audit(row)">审核</el-button><el-button v-if="row.status === 'DRAFT'" link type="danger" @click="cancel(row)">取消</el-button></template></el-table-column>
      </el-table>
      <el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" class="pagination" @change="load" />
    </el-card>

    <el-dialog v-model="dialogVisible" title="新增库存盘点" width="760px"><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><el-row :gutter="12"><el-col :span="12"><el-form-item label="盘点仓库" prop="warehouseId"><el-select v-model="form.warehouseId" style="width:100%"><el-option v-for="warehouse in warehouses" :key="warehouse.id" :label="warehouse.name" :value="warehouse.id!" /></el-select></el-form-item></el-col><el-col :span="6"><el-form-item label="盘点日期"><el-date-picker v-model="form.checkDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></el-col><el-col :span="6"><el-form-item label="盘点类型"><el-select v-model="form.checkType" style="width:100%"><el-option label="全盘" value="FULL" /><el-option label="部分盘" value="PARTIAL" /></el-select></el-form-item></el-col></el-row><el-table :data="form.items" border size="small"><el-table-column label="商品" min-width="250"><template #default="{ $index }"><el-select v-model="form.items[$index].productId" filterable placeholder="选择商品" style="width:100%"><el-option v-for="product in products" :key="product.id" :label="product.name + (product.spec ? ` / ${product.spec}` : '')" :value="product.id!" /></el-select></template></el-table-column><el-table-column label="参考单价" width="140"><template #default="{ $index }"><el-input-number v-model="form.items[$index].price" :min="0" :precision="2" :controls="false" style="width:100%" /></template></el-table-column><el-table-column label="操作" width="80"><template #default="{ $index }"><el-button link type="danger" @click="form.items.splice($index,1)">删除</el-button></template></el-table-column></el-table><el-button plain size="small" :icon="Plus" class="add-line" @click="addItem">添加一行</el-button><el-form-item label="备注" class="remark"><el-input v-model="form.remark" maxlength="500" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存草稿</el-button></template></el-dialog>

    <el-dialog v-model="resultVisible" title="录入盘点结果" width="820px"><el-table :data="resultItems" border size="small"><el-table-column prop="productName" label="商品" min-width="200" /><el-table-column prop="systemQty" label="系统数量" width="120" align="right" /><el-table-column label="实际数量" width="150"><template #default="{ row }"><el-input-number v-model="row.actualQty" :min="0" :precision="4" :controls="false" style="width:100%" /></template></el-table-column><el-table-column label="差异" width="110" align="right"><template #default="{ row }">{{ ((row.actualQty ?? 0) - (row.systemQty ?? 0)).toFixed(4) }}</template></el-table-column><el-table-column label="备注" min-width="150"><template #default="{ row }"><el-input v-model="row.note" /></template></el-table-column></el-table><template #footer><el-button @click="resultVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitResult">提交结果</el-button></template></el-dialog>

    <el-dialog v-model="detailVisible" title="库存盘点详情" width="840px"><template v-if="detail"><el-descriptions :column="3" border><el-descriptions-item label="盘点单号">{{ detail.docNo }}</el-descriptions-item><el-descriptions-item label="仓库">{{ detail.warehouseName || warehouseName(detail.warehouseId) }}</el-descriptions-item><el-descriptions-item label="盘点日期">{{ detail.checkDate }}</el-descriptions-item><el-descriptions-item label="类型">{{ checkTypeLabel(detail.checkType) }}</el-descriptions-item><el-descriptions-item label="状态">{{ statusLabel(detail.status) }}</el-descriptions-item><el-descriptions-item label="备注">{{ detail.remark || '—' }}</el-descriptions-item></el-descriptions><el-table :data="detail.items" border size="small" class="detail-table"><el-table-column prop="productName" label="商品" min-width="180" /><el-table-column prop="systemQty" label="系统数量" width="120" align="right" /><el-table-column prop="actualQty" label="实际数量" width="120" align="right" /><el-table-column prop="diffQty" label="差异数量" width="120" align="right" /><el-table-column prop="price" label="单价" width="100" align="right" /><el-table-column prop="note" label="备注" min-width="150" /></el-table></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { FormInstance, FormRules } from 'element-plus'
import { Plus, Search } from '@element-plus/icons-vue'
import { inventoryCheckApi } from '@/api/inventory'
import { warehouseApi, type Warehouse } from '@/api/warehouse'
import { productApi, type Product } from '@/api/product'
type Check = { id:number; docNo:string; warehouseId:number; checkDate:string; status:string; checkType:string; totalItems:number; totalAmount:number; diffItems:number; diffAmount:number; warehouseName?:string; createdAt:string }
type CheckDetail = Check & { items:Array<{ id?:number; productId:number; productName?:string; systemQty:number; actualQty?:number; diffQty?:number; price:number; note?:string }>; remark?:string }
const statusOptions=[{value:'DRAFT',label:'草稿'},{value:'AUDITING',label:'盘点中'},{value:'AUDITED',label:'已盘点'},{value:'CANCELLED',label:'已取消'}]
const loading=ref(false),saving=ref(false),records=ref<Check[]>([]),total=ref(0),warehouses=ref<Warehouse[]>([]),products=ref<Product[]>([]),detail=ref<CheckDetail>(),resultItems=ref<CheckDetail['items']>([])
const query=reactive({page:1,size:10,keyword:'',status:'',warehouseId:undefined as number|undefined}),dialogVisible=ref(false),detailVisible=ref(false),resultVisible=ref(false),formRef=ref<FormInstance>()
const form=reactive({warehouseId:undefined as number|undefined,checkDate:new Date().toISOString().slice(0,10),checkType:'FULL',remark:'',items:[] as Array<{productId?:number;price:number}>}),rules:FormRules={warehouseId:[{required:true,message:'请选择盘点仓库',trigger:'change'}]}
const warehouseMap=computed(()=>new Map(warehouses.value.map((item)=>[item.id!,item.name]))),money=(value?:number)=>(value??0).toFixed(2),warehouseName=(id?:number)=>id?warehouseMap.value.get(id)||'—':'—',statusLabel=(status:string)=>statusOptions.find((item)=>item.value===status)?.label||status,checkTypeLabel=(type:string)=>type==='PARTIAL'?'部分盘':'全盘',statusType=(status:string)=>status==='AUDITED'?'success':status==='CANCELLED'?'info':status==='AUDITING'?'primary':'warning'
async function load(){loading.value=true;try{const data=await inventoryCheckApi.getCheckList({...query,keyword:query.keyword||undefined,status:query.status||undefined});records.value=data.records;total.value=data.total}finally{loading.value=false}}
function search(){query.page=1;load()} function addItem(){form.items.push({productId:undefined,price:0})} function openCreate(){Object.assign(form,{warehouseId:undefined,checkDate:new Date().toISOString().slice(0,10),checkType:'FULL',remark:'',items:[]});addItem();dialogVisible.value=true}
async function save(){const valid=await formRef.value?.validate().catch(()=>false);if(!valid||!form.items.length||form.items.some((item)=>!item.productId)){if(!form.items.length||form.items.some((item)=>!item.productId))ElMessage.warning('请为每一行选择商品');return}saving.value=true;try{await inventoryCheckApi.createCheck({warehouseId:form.warehouseId!,checkDate:form.checkDate,checkType:form.checkType,remark:form.remark,items:form.items.map((item)=>({productId:item.productId!,price:item.price}))});ElMessage.success('盘点草稿已保存');dialogVisible.value=false;await load()}finally{saving.value=false}}
async function showDetail(id:number){detail.value=await inventoryCheckApi.getCheckDetail(id);detailVisible.value=true}
async function action(row:Check,name:string,callback:()=>Promise<unknown>){try{await ElMessageBox.confirm(`${name}后单据状态将更新，确认${name} ${row.docNo}?`,`${name}确认`,{type:'warning'});await callback();ElMessage.success(`${name}成功`);await load()}catch(error){if(error!=='cancel')throw error}}
const start=(row:Check)=>action(row,'开始盘点',()=>inventoryCheckApi.startCheck(row.id));const audit=(row:Check)=>action(row,'审核',()=>inventoryCheckApi.auditCheck(row.id));const cancel=(row:Check)=>action(row,'取消',()=>inventoryCheckApi.cancelCheck(row.id))
async function openResult(row:Check){detail.value=await inventoryCheckApi.getCheckDetail(row.id);resultItems.value=(detail.value.items||[]).map((item)=>({...item,actualQty:item.actualQty??item.systemQty}));resultVisible.value=true}
async function submitResult(){if(!detail.value)return;saving.value=true;try{await inventoryCheckApi.submitCheckResult(detail.value.id,{items:resultItems.value.map((item)=>({productId:item.productId,actualQty:item.actualQty??0,note:item.note}))});ElMessage.success('盘点结果已提交');resultVisible.value=false;await load()}finally{saving.value=false}}
onMounted(async()=>{const [warehouseResult,productResult]=await Promise.all([warehouseApi.listAll(),productApi.page({page:1,size:500})]);warehouses.value=warehouseResult;products.value=productResult.records;await load()})
</script>
<style scoped>.toolbar{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}.pagination{margin-top:16px;justify-content:flex-end}.add-line{margin-top:8px}.remark{margin-top:16px}.detail-table{margin-top:16px}</style>
